#!/usr/bin/env bash

namespace="System/Linux"
unit="Percent"
metric_name=
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimAs="[ {\"Name\": \"AutoScalingGroupName\", \"Value\": \"$3\"} ]"
value=

info=$(df -x tmpfs -x devtmpfs | tail -n+2)
metrics=""

while read line; do
    metric_name=
    value=
    # Get location of device mount
    mount=${line##* }
    mount=${mount:1}
    # Get device percent used
    value=${line%%\%*}
    value=${value##* }
    if [ "$mount" = "" ]; then
        metric_name="rootDiskUtilization"
    else
        metric_name="${mount}DiskUtilization"
    fi

    metrics="$metrics,{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}"
    metrics="$metrics,{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimAs, \"Value\": \"$value\", \"Unit\": \"$unit\"}"
done <<< "$info"

metrics=$(sed  's/^,//' <<< $metrics); # Strip leading comma

aws cloudwatch put-metric-data \
--region $region \
--namespace "$namespace" \
--metric-data "[ $metrics ]"
