#!/usr/bin/env bash

set -e

if which docker > /dev/null 2>&1 && docker info | grep "Storage Driver: devicemapper" > /dev/null 2>&1; then
    free=$(docker info | grep "Data Space Used")
    free=${free##*: }
    unit=${free##* }
    free=${free%% *}
    [ "$unit" == "KB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000}' <<< ${free})
    [ "$unit" == "MB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000}' <<< ${free})
    [ "$unit" == "GB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000000}' <<< ${free})
    [ "$unit" == "TB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000000000}' <<< ${free})

    total=$(docker info | grep "Data Space Total")
    total=${total##*: }
    unit=${total##* }
    total=${total%% *}
    [ "$unit" == "KB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000}' <<< ${free})
    [ "$unit" == "MB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000}' <<< ${total})
    [ "$unit" == "GB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000000}' <<< ${total})
    [ "$unit" == "TB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000000000}' <<< ${total})

    value=$(awk '{ printf "%2.2f" , ($1 * 100)/$2}' <<< "${free} ${total}")
    echo "dockerDiskUtilization;Percent;$value"
fi
