#!/usr/bin/env bash

set -e

if which docker > /dev/null 2>&1 && docker info | grep "Storage Driver: devicemapper" > /dev/null 2>&1; then
    free=$(docker info | grep "Data Space Used")
    free=${free##*: }
    value=${free%%?B}
    unit=${free##${value}}
    [ "$unit" == "KB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000}' <<< ${value})
    [ "$unit" == "MB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000}' <<< ${value})
    [ "$unit" == "GB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000000}' <<< ${value})
    [ "$unit" == "TB" ] && free=$(awk '{ printf "%.0f" , $1 * 1000000000000}' <<< ${value})

    total=$(docker info | grep "Data Space Total")
    total=${total##*: }
    value=${total%%?B}
    unit=${total##${value}}
    [ "$unit" == "KB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000}' <<< ${value})
    [ "$unit" == "MB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000}' <<< ${value})
    [ "$unit" == "GB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000000}' <<< ${value})
    [ "$unit" == "TB" ] && total=$(awk '{ printf "%.0f" , $1 * 1000000000000}' <<< ${value})

    value=$(awk '{ printf "%2.2f" , ($1 * 100)/$2}' <<< "${free} ${total}")
    echo "dockerDiskUtilization;Percent;$value"
fi
