#!/usr/bin/env bash

namespace="System/Linux"
metric_name="LoadAverage"
unit="Count"
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimGr="[ {\"Name\": \"Group\", \"Value\": \"$3\"} ]"
value=$(cat /proc/loadavg |cut -d " " -f 1)

aws cloudwatch put-metric-data \
--region $region \
--namespace "$namespace" \
--metric-data "\
[\
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}, \
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimGr, \"Value\": \"$value\", \"Unit\": \"$unit\"}\
]"
