#!/usr/bin/env bash

namespace="System/Linux"
metric_name="MemoryUtilization"
unit="Percent"
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimAs="[ {\"Name\": \"AutoScalingGroupName\", \"Value\": \"$3\"} ]"
value=

total=$(free -m | grep "Mem" | tr -s " " | cut -d " " -f 2)
free=$(free -m | grep "buffers/cache" | tr -s " " | cut -d " " -f 4)
value=$((100 - (( (($free * 100)) / $total)) ))

aws cloudwatch put-metric-data \
--region $region \
--namespace "$namespace" \
--metric-data "\
[\
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}, \
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimAs, \"Value\": \"$value\", \"Unit\": \"$unit\"}\
]"
