#!/usr/bin/env bash

set -e

metric_name="MemoryUtilization"
unit="Percent"

total=$(cat /proc/meminfo | grep "MemTotal" | tr -s " " | cut -d " " -f 2)
free=$(cat /proc/meminfo | grep "MemAvailable" | tr -s " " | cut -d " " -f 2)
value=$((100 - (( (($free * 100)) / $total)) ))

echo "$metric_name;$unit;$value"
