#!/usr/bin/env bash

region=$1
namespace="System/Linux"
metric_name="MemoryUtilization"
dimensions="InstanceId=$2,AutoScalingGroupName=$3"
unit="Percent"
value=

total=$(free -m | grep "Mem" | tr -s " " | cut -d " " -f 2)
free=$(free -m | grep "buffers/cache" | tr -s " " | cut -d " " -f 4)
value=$((100 - (( (($free * 100)) / $total)) ))

aws cloudwatch put-metric-data \
    --region $region \
    --namespace $namespace \
    --metric-name $metric_name \
    --dimensions $dimensions \
    --value $value \
    --unit $unit
