#!/usr/bin/env bash

namespace="System/Linux"
metric_name="NetworkIn"
unit="Bytes"
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimGr="[ {\"Name\": \"AutoScalingGroupName\", \"Value\": \"$3\"} ]"
value=

prev=$(cat /tmp/cwput_rx_bytes)
rx=$(cat /sys/class/net/eth0/statistics/rx_bytes)

if [ -z "$prev" ]; then
    echo "$rx" > /tmp/cwput_rx_bytes
else
    value=$(($rx - $prev))
    echo "$rx" > /tmp/cwput_rx_bytes
    aws cloudwatch put-metric-data \
    --region $region \
    --namespace "$namespace" \
    --metric-data "\
    [\
    {\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}, \
    {\"MetricName\": \"$metric_name\", \"Dimensions\": $dimGr, \"Value\": \"$value\", \"Unit\": \"$unit\"}\
    ]"
fi
