#!/usr/bin/env bash

set -e

CWPUT_NET=${CWPUT_NET:-"eth0"}

namespace="System/Linux"
metric_name="NetworkOut"
unit="Bytes"
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimGr="[ {\"Name\": \"AutoScalingGroupName\", \"Value\": \"$3\"} ]"
value=

tx=$(cat /sys/class/net/$CWPUT_NET/statistics/tx_bytes)

if [ ! -f /tmp/cwput_tx_bytes ]; then
    echo "$tx" > /tmp/cwput_tx_bytes
fi

prev=$(cat /tmp/cwput_tx_bytes)

value=$(($tx - $prev))
echo "$tx" > /tmp/cwput_tx_bytes
aws cloudwatch put-metric-data \
--region $region \
--namespace "$namespace" \
--metric-data "\
[\
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}, \
{\"MetricName\": \"$metric_name\", \"Dimensions\": $dimGr, \"Value\": \"$value\", \"Unit\": \"$unit\"}\
]"

