#!/usr/bin/env bash

namespace="System/Linux"
metric_name="NetworkOut"
unit="Bytes"
region=$1
dimId="[ {\"Name\": \"InstanceId\", \"Value\": \"$2\"} ]"
dimGr="[ {\"Name\": \"AutoScalingGroupName\", \"Value\": \"$3\"} ]"
value=

prev=$(cat /tmp/cwput_tx_bytes)
tx=$(cat /sys/class/net/eth0/statistics/tx_bytes)

if [ -z "$prev" ]; then
    echo "$tx" > /tmp/cwput_tx_bytes
else
    value=$(($tx - $prev))
    echo "$tx" > /tmp/cwput_tx_bytes
    aws cloudwatch put-metric-data \
    --region $region \
    --namespace "$namespace" \
    --metric-data "\
    [\
    {\"MetricName\": \"$metric_name\", \"Dimensions\": $dimId, \"Value\": \"$value\", \"Unit\": \"$unit\"}, \
    {\"MetricName\": \"$metric_name\", \"Dimensions\": $dimGr, \"Value\": \"$value\", \"Unit\": \"$unit\"}\
    ]"
fi
