#!/usr/bin/env bash

set -e

CWPUT_NET=${CWPUT_NET:-"eth0"}

metric_name="NetworkOut"
unit="Bytes"

tx=$(cat /sys/class/net/$CWPUT_NET/statistics/tx_bytes)

if [ ! -f /tmp/cwput_tx_bytes ]; then
    echo "$tx" > /tmp/cwput_tx_bytes
fi

prev=$(cat /tmp/cwput_tx_bytes)

value=$(($tx - $prev))
echo "$tx" > /tmp/cwput_tx_bytes

echo "$metric_name;$unit;$value"
